Finished lecture 2
ziperjohn/dev-academy-ios pull request #2
Opened 2023-07-18 15:28 UTC by ziperjohn

Finished lecture 2, Created DataService

2023-07-19 08:52 UTC, mikolasstuchlik requested changes, later dismissed

2023-07-19 08:52 UTC, mikolasstuchlik commented on DevAcademy/SwiftBasic.swift
> +}
![anime-anime-blush](https://github.com/ziperjohn/dev-academy-ios/assets/42004728/a72dd3f5-6328-4015-bcb9-9c5c7044c2ae)

2023-07-19 08:52 UTC, mikolasstuchlik commented on DevAcademy/SwiftBasic.swift
> +    let druh: Kind
⚠️ Potřebujeme tam `PossibleKind` :) 

```suggestion
    let druh: PossibleKind
```

2023-07-19 08:52 UTC, mikolasstuchlik commented on DevAcademy/SwiftBasic.swift
> +    static var shared: DataService = .init()
✳️ pokud dáme `var`, tak se nám může stát, že tu proměnnou omylem nahradíme jinou instancí
```suggestion
    static let shared: DataService = .init()
```

2023-07-19 08:52 UTC, mikolasstuchlik commented on DevAcademy/SwiftBasic.swift
> +        }
⚠️ Volání Timeru je v pořádku, je ale potřeba trochu upravit logiku.

1. **Před** voláním timeru zkontrolujme, jestli už máme nějaká `data`, která nejsou `nil`
2. Pokud ano, zavolejme `closure` a skončeme.
3. Pokud ne, pokračujme voláním timeru.
4. Až vyprší timer, nastavme `data` na hodnotu `mockData`, zavolejme closure a skončeme

2023-07-24 14:34 UTC, eRDe33 commented on DevAcademy/SwiftBasic.swift
> +        guard self.data == nil else {
v pripade, ze mame data, tak se nejedna o chybu, ale chceme vratit ta data (omlouvam za zmateni na workshopu, ten FakeFetchError v ramci tohoto cviceni nakonec nevyuzijeme 😉).

Proto bych mozna namisto guard volil if a mohlo by to vypadat nejak takhle:

```Swift
if let data = data {
    completion(data)
    return
}
```

2023-07-24 14:34 UTC, eRDe33 commented on DevAcademy/SwiftBasic.swift
> +            self.data = Result.success(DataService.mockData)
diky te referenci na `self.data` nam tu vznikne retain cycle, takze je potreba si sem ten `self` predat jako `weak`.

Zaroven abys nemusel jak do tech `self.data` tak to te `completion` kopirovat ten Result, tak je fajn si udelat pomocnou promennou, ve ktere budes mit ty nove data.

Mohlo by to vypadat nejak takhle:
```Swift
Timer.scheduledTimer(withTimeInterval: 2.0, repeats: false) { [weak self] _ in
             let newData = Result.success(DataService.mockData)
             self?.data = newData
             completion(newData)
}
```

2023-07-25 12:12 UTC, eRDe33 approved these changes
👍

2023-07-25 12:13 UTC, merged